// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk8OcLTPLc5Rg9CI9SQcEZE8Xq4pT0RNo',
    appId: '1:617219390885:web:c5834d1301eccc9ebf3c4c',
    messagingSenderId: '617219390885',
    projectId: 'chatapppratice-fcf5f',
    authDomain: 'chatapppratice-fcf5f.firebaseapp.com',
    storageBucket: 'chatapppratice-fcf5f.firebasestorage.app',
    measurementId: 'G-C5H2GWBNCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFkKdgPafcmwID_-XReIpCS9GfO7dOnM',
    appId: '1:617219390885:android:0f5ce42a97e4a9ffbf3c4c',
    messagingSenderId: '617219390885',
    projectId: 'chatapppratice-fcf5f',
    storageBucket: 'chatapppratice-fcf5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEVZet5rVX3kb2T8_KqzxlBdKILJCLsRI',
    appId: '1:617219390885:ios:b00288efdbc2d7b1bf3c4c',
    messagingSenderId: '617219390885',
    projectId: 'chatapppratice-fcf5f',
    storageBucket: 'chatapppratice-fcf5f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEVZet5rVX3kb2T8_KqzxlBdKILJCLsRI',
    appId: '1:617219390885:ios:b00288efdbc2d7b1bf3c4c',
    messagingSenderId: '617219390885',
    projectId: 'chatapppratice-fcf5f',
    storageBucket: 'chatapppratice-fcf5f.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk8OcLTPLc5Rg9CI9SQcEZE8Xq4pT0RNo',
    appId: '1:617219390885:web:04f16e21c509f499bf3c4c',
    messagingSenderId: '617219390885',
    projectId: 'chatapppratice-fcf5f',
    authDomain: 'chatapppratice-fcf5f.firebaseapp.com',
    storageBucket: 'chatapppratice-fcf5f.firebasestorage.app',
    measurementId: 'G-DC74WHT19S',
  );

}